### ISSUE TITLE
prioritize ASGS runs on specific HPC resources

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#601] opened 2021-07-25 15:48 UTC
Is it technically possible for ASGS to prioritize ASGS instances to be run on dedicated HPC allocations? I know this is a difficult question and not to achieve quickly, but would it be possible to let's say run TX meshes with the highest priority on TACC, the LA mesh with the highest priority on LSU allocations, etc?

**Comment by wwlwpd** [comment] 2021-07-25 16:06
No, there is no way to coordinate among mesh runs; And I do not recommend we consider the ability to "schedule" local HPC resources given multiple runs. It would require a higher level scheduler and create another "meta layer" above all ASGS instances running on the same machine.

**Comment by jasonfleming** [comment] 2021-07-26 13:05
We manually control what mesh each ASGS runs, what machine it runs on, whether it is using priority access via the scenario package spreadsheet, which sort of acts as that meta layer @wwlwpd mentioned. Hopefully that is working well for everyone. If not, please let everyone know, feedback is always welcomed! :-) But the ASGS instances can't interact with each other, as @wwlwpd mentioned, which is by design.

**Comment by carolakaiser** [comment] 2021-07-26 13:17
Thanks for the comments @wwlwpd and @jasonfleming.
How can we accomplish that runs that are in the interest of CERA or UT Austin and run on their allocations get the chance to come through in time when many runs get executed on those allocations? Is then the only chance to reduce the number of runs on a HPC resource or distribute them in a smart way between the available allocations?

**Comment by carolakaiser** [comment] 2021-07-26 14:37
** deleted the last comment to make it a more general question that applies to all ASGS consumers **

Thanks for the comments @wwlwpd and @jasonfleming.
How can we accomplish that runs that are in the interest of ASGS consumers and run on their allocations get the chance to come through in time when many runs get executed on those allocations? Is then the only chance to reduce the number of runs on a HPC resource or distribute them in a smart way between the available allocations?

**Comment by wwlwpd** [comment] 2021-07-29 01:08
interestingly, this is more or less an open research question in HPC and was addressed in part back in the glory days of cct by someone you might remember, https://www.cct.lsu.edu/research/cyber-advancement/harc

summary: it's a hard problem to solve

**Comment by wwlwpd** [comment] 2021-08-10 02:35
any chance we can close this?

**Comment by jasonfleming** [comment] 2021-08-10 12:25
Yes, we can accomplish this through the selective use of priority access.

**Closed by jasonfleming** 2021-08-10 12:25 UTC
Labels: question, discussion
