### ISSUE TITLE
Tab autocomplete not working in ASGSH

### ISSUE THREAD

**Issue by notstarboard** [StormSurgeLive/asgs#1171] opened 2023-07-14 14:52 UTC
Hi All! I stood up an ASGS instance about a month ago and tab autocomplete doesn't work from within ASGSH. See this screenshot for an example:

![image](https://github.com/StormSurgeLive/asgs/assets/16867209/653d0a43-60e4-4db7-8e02-a2489f739d23)

Not only does ASGSH not autocomplete "gfs" here when I hit tab, but double tapping tab lists all folders instead of just the ones that start with "g".

I see #799 is out there to try to enhance tab autocomplete, but it seems like it's going in the other direction! :smile:

**Comment by jasonfleming** [comment] 2023-07-14 17:39
Hey @notstarboard I think the tab autocomplete works the same in `asgsh` as it does in regular `bash`. Since `cd` is a `bash` command, the response is the same as it would be in `bash`. I'm not sure why it does not autocomplete `gfs` when you spot it the `g`. What do you get when you try this with `define` (a command specific to `asgsh`)?

**Comment by notstarboard** [comment] 2023-07-14 18:31
That's how every other instance I've set up works, but I have no issues with tab autocomplete until I run asgsh and then they happen right away.

It seems to work as intended for ASGS specific commands:

![image](https://github.com/StormSurgeLive/asgs/assets/16867209/28c887d5-21b9-439b-a286-834647722501)

**Comment by jasonfleming** [comment] 2023-07-14 19:00
Is this the latest master branch?

**Comment by notstarboard** [comment] 2023-07-14 19:43
It's about a month old! I can set up another instance and see if that fixes it if you can't reproduce it on a newer instance.

**Comment by jasonfleming** [comment] 2023-07-14 20:41
I was not able to reproduce it on my desktop machine (ubuntu 20.04LTS ... "debian" for ASGS purposes). What operating system are you working on?

**Comment by notstarboard** [comment] 2023-07-14 22:32
Unity is the same: Ubuntu 20.04.6 LTS. When I get a chance I'll set up another instance and see whether or not I hit the same issue!

**Comment by wwlwpd** [comment] 2023-07-18 07:30
I can't reproduce this either. The way that tab completion works, is that it's context sensitive. So in the case of `cd`,  your gonna want to check to see if you have  something defined for `cd`, it should be in a bash script and if the convention holds, defined using a bash function, `_cd`.

**Comment by wwlwpd** [comment] 2023-07-31 03:24
@notstarboard I am going to close this out, please re-open if you find some steps you'd like me to try reproduce it.

**Comment by notstarboard** [comment] 2023-08-25 21:29
Hi all! Just wanted to submit another two data points on this - Pranav, Isaac's new student, just installed an ASGS instance on Unity and he's also having the tab autocomplete issue. Meanwhile the tab autocomplete on my still-somewhat-broken new instance on Hatteras is working just fine. So it does seem like a consistent, but system-specific issue.

**Comment by wwlwpd** [comment] 2023-08-27 07:38
> Hi all! Just wanted to submit another two data points on this - Pranav, Isaac's new student, just installed an ASGS instance on Unity and he's also having the tab autocomplete issue. Meanwhile the tab autocomplete on my still-somewhat-broken new instance on Hatteras is working just fine. So it does seem like a consistent, but system-specific issue

It's one of those things that I need access to the system on which it's not working in order to debug/fix. Can you get me access?

**Comment by notstarboard** [comment] 2023-08-30 23:55
Makes sense! I reached out to one of the Unity admins a few days ago about getting you access and I think they can get you a temporary account. I'm going to message back on that chain tomorrow because it seems to have gotten stale.

**Comment by notstarboard** [comment] 2023-08-31 15:51
I think the Unity admin I reached out to solved the issue! According to him: 

_The issue is that _init_completion is an internal name used by bash already and they redefined it in asgs/etc/bash-completions/init. I changed the name of the function to _asgsinit_completion and it seems to have fixed it._

Does that make sense to you and seem like a fair fix? Or would you still like to test it out on Unity?

**Comment by jasonfleming** [comment] 2023-09-06 09:57
I am running into this on Frontera at TACC. Let's reopen this issue and see if we can apply the fix from @notstarboard , thank you!!

**Comment by wwlwpd** [comment] 2023-09-06 18:02
> I am running into this on Frontera at TACC. Let's reopen this issue and see if we can apply the fix from @notstarboard , thank you!!

What keystroke combination?

**Comment by jasonfleming** [comment] 2023-09-06 18:12
It isn't really a keystroke combination, it's just that my normal tab completion doesn't work at all in asgsh on Frontera. I will make a separate fresh installation of asgs to see if I can come up with a concise set of steps to reproduce this on Frontera.

**Comment by wwlwpd** [comment] 2023-09-06 18:55
I can reproduce it. Seems the default tab completions are getting purged. On it...

**Comment by wwlwpd** [comment] 2023-09-06 19:03
@notstarboard @jasonfleming Unity's systadmin's suggestion seems to have resolved it. Thank you for your patience, will push the fix momentarily.

**Closed** 2023-09-06 19:07 UTC
Labels: bug, verify suggested workaround, important non-critical, please attempt to reproduce, installation, Unity@MGHPCC, UX
